# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'splash_screen.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets
from PyQt5.QtCore import QTimer
from login import Login_Window


class Ui_Splash_Screen(object):
    def setupUi(self, Splash_Screen):

        Splash_Screen.setObjectName("Splash_Screen")
        Splash_Screen.resize(500, 500)
        Splash_Screen.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        Splash_Screen.setAttribute(QtCore.Qt.WA_TranslucentBackground)
        self.splash_logo = QtWidgets.QFrame(Splash_Screen)
        self.splash_logo.setGeometry(QtCore.QRect(100, 100, 300, 300))
        self.splash_logo.setStyleSheet("border-image: url(:/images/thesis_system_logo_with_no_text.png);")
        self.splash_logo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.splash_logo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.splash_logo.setObjectName("splash_logo")

        self.retranslateUi(Splash_Screen)
        QtCore.QMetaObject.connectSlotsByName(Splash_Screen)

        QTimer.singleShot(2000, self.stopSplash)

    def retranslateUi(self, Splash_Screen):
        _translate = QtCore.QCoreApplication.translate
        Splash_Screen.setWindowTitle(_translate("Splash_Screen", "Form"))



    def stopSplash(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Login_Window()
        self.ui.setupUi(self.window)
        self.window.show()
        Splash_Screen.hide()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Splash_Screen = QtWidgets.QWidget()
    ui = Ui_Splash_Screen()
    ui.setupUi(Splash_Screen)
    Splash_Screen.show()
    sys.exit(app.exec_())
